version: "2"

services:
    ## en-marche.fr
    ###############
    enmarche.dev:
        build:
            context: docker/dev
        depends_on:
            - enmarche_db
            - enmarche_redis
            - auth.enmarche.dev
            - api.enmarche.dev
            - rabbitmq
        volumes:
            - .:/app

    enmarche_db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root

    enmarche_redis:
        image: redis:3.2

    ## auth.en-marche.fr
    ####################
    auth.enmarche.dev:
        image: larem/auth.en-marche.fr
        volumes:
          - ./.env.auth:/app/.env
        depends_on:
            - rabbitmq

    ## api.en-marche.fr
    ####################
    api.enmarche.dev:
        image: larem/api.en-marche.fr
        volumes:
          - ./.env.api:/app/.env
        depends_on:
            - rabbitmq

    ## common
    ####################
    rabbitmq:
        image: rabbitmq:3-management
